lib/hou_web/router.ex
defmodule HouWeb.Router do
  use HouWeb, :router

  import HouWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {HouWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HouWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", HouWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: HouWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", HouWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", HouWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", HouWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/hou_web/controllers/user_registration_controller.ex
defmodule HouWeb.UserRegistrationController do
  use HouWeb, :controller

  alias Hou.Accounts
  alias Hou.Accounts.User
  alias HouWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :confirm, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/hou_web/views/user_registration_view.ex
defmodule HouWeb.UserRegistrationView do
  use HouWeb, :view
end

lib/hou_web/templates/user_registration/new.html.eex
<div class="login_box">

<h1>Registrar</h1>
<%# <p class="login_text">Sua mãe é nossa heheheeh</p> %>

<div class="input_box">
<%= form_for @changeset, Routes.user_registration_path(@conn, :create), fn f -> %>
  <%= if @changeset.action do %>

  <% end %>

  <%= label f, :email %>
  <%= email_input f, :email, required: true %>
  <%= error_tag f, :email %>
<div class="login_pass">
  <%= label f, :password %>
  <%= password_input f, :password, required: true %>
  <%= error_tag f, :password %>
<div>
  <div class="login_button">
    <%= submit "Registrar" %>
  </div>
<% end %>
</div>

<p class="login_reg-cad">
  <%= link "Login", to: Routes.user_session_path(@conn, :new) %>
  <%= link "Esqueceu a senha?", to: Routes.user_reset_password_path(@conn, :new) %>
</p>

<div class="alert alert-danger">
      <p>Ops, algo deu errado! Verifique os erros abaixo.</p>
    </div>
</div>